In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [" Amit ", "Rahul", "Priya", "Rahul", "Neha "],
    "Age": [25, np.nan, 28, 32, 35],
    "Salary": [40000, 65000, 55000, 65000, np.nan],
    "City": ["Indore", "Mumbai", "Delhi", "Mumbai", " Indore "]
})

In [12]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   30.000000  56250.000000
std     3.807887  10231.690965
min    25.000000  40000.000000
25%    28.000000  55000.000000
50%    30.000000  56250.000000
75%    32.000000  65000.000000
max    35.000000  65000.000000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Salary  5 non-null      float64
 3   City    5 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 288.0 bytes

In [4]:
df.isna().sum()

Name      0
Age       1
Salary    1
City      0
dtype: int64

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df.head()

     Name   Age   Salary      City
0   Amit   25.0  40000.0    Indore
1   Rahul  30.0  65000.0    Mumbai
2   Priya  28.0  55000.0     Delhi
3   Rahul  32.0  65000.0    Mumbai
4   Neha   35.0  56250.0   Indore

In [6]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Name"] = df["Name"].str.strip()
df.head()

    Name   Age   Salary      City
0   Amit  25.0  40000.0    Indore
1  Rahul  30.0  65000.0    Mumbai
2  Priya  28.0  55000.0     Delhi
3  Rahul  32.0  65000.0    Mumbai
4   Neha  35.0  56250.0   Indore

In [10]:
df.dtypes

Name          str
Age       float64
Salary    float64
City          str
dtype: object

In [11]:
df["Age"] = df["Age"].astype("int64")
df.dtypes

Name          str
Age         int64
Salary    float64
City          str
dtype: object