In [2]:
import pandas as pd

data = {
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Karan", "Vikas"],
    "Department": ["QA", "Dev", "QA", "Dev", "QA", "Dev"],
    "Salary": [40000, 65000, 55000, 75000, 38000, 70000],
    "Experience": [2, 5, 4, 7, 1, 6]
}

df = pd.DataFrame(data)
print(df)

    Name Department  Salary  Experience
0   Amit         QA   40000           2
1  Rahul        Dev   65000           5
2  Priya         QA   55000           4
3   Neha        Dev   75000           7
4  Karan         QA   38000           1
5  Vikas        Dev   70000           6

In [3]:
df.groupby("Department")["Salary"].mean()

Department
Dev    70000.000000
QA     44333.333333
Name: Salary, dtype: float64

In [4]:
df.groupby("Department")["Experience"].sum()

Department
Dev    18
QA      7
Name: Experience, dtype: int64

In [5]:
df.groupby("Department")["Name"].count()

Department
Dev    3
QA     3
Name: Name, dtype: int64

In [6]:
df.groupby("Department")["Salary"].agg(
    ["min", "max", "mean"]
)

              min    max          mean
Department
Dev         65000  75000  70000.000000
QA          38000  55000  44333.333333

In [14]:
df1=df.groupby("Department")["Salary"].mean()
print(df1.idxmax())

Dev

In [15]:
data = {
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Karan", "Vikas", "Riya"],
    "Department": ["QA", "Dev", "QA", "Dev", "QA", "Dev", "QA"],
    "Salary": [40000, 65000, 55000, 75000, 38000, 70000, 60000],
    "Experience": [2, 5, 4, 7, 1, 6, 5]
}

df2 = pd.DataFrame(data)

In [16]:
df2.groupby("Department")["Salary"].agg(
    ["min", "max", "mean"])

              min    max     mean
Department
Dev         65000  75000  70000.0
QA          38000  60000  48250.0

In [17]:
df3=df2.groupby("Department")["Salary"].agg(
    ["min", "max", "mean"])
print(df3)

              min    max     mean
Department
Dev         65000  75000  70000.0
QA          38000  60000  48250.0

In [18]:
df3.sort_values(by="mean", ascending=False)

              min    max     mean
Department
Dev         65000  75000  70000.0
QA          38000  60000  48250.0

In [19]:
result = df.groupby("Department").agg(
    EmployeeCount=("Name", "count"),
    AverageSalary=("Salary", "mean"),
    AverageExperience=("Experience", "mean")
)

print(result)

            EmployeeCount  AverageSalary  AverageExperience
Department
Dev                     3   70000.000000           6.000000
QA                      3   44333.333333           2.333333