In [2]:
import pandas as pd
data = {
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Karan"],
    "Age": [25, 32, 28, 35, 24],
    "Salary": [40000, 65000, 55000, 75000, 38000],
    "City": ["Indore", "Mumbai", "Delhi", "Indore", "Pune"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Salary    City
0   Amit   25   40000  Indore
1  Rahul   32   65000  Mumbai
2  Priya   28   55000   Delhi
3   Neha   35   75000  Indore
4  Karan   24   38000    Pune

In [3]:
df.sort_values("Salary")

    Name  Age  Salary    City
4  Karan   24   38000    Pune
0   Amit   25   40000  Indore
2  Priya   28   55000   Delhi
1  Rahul   32   65000  Mumbai
3   Neha   35   75000  Indore

In [4]:
df.sort_values("Salary", ascending=False)

    Name  Age  Salary    City
3   Neha   35   75000  Indore
1  Rahul   32   65000  Mumbai
2  Priya   28   55000   Delhi
0   Amit   25   40000  Indore
4  Karan   24   38000    Pune

In [5]:
df.sort_values(
    ["City", "Salary"],
    ascending=[True, False]
)

    Name  Age  Salary    City
2  Priya   28   55000   Delhi
3   Neha   35   75000  Indore
0   Amit   25   40000  Indore
1  Rahul   32   65000  Mumbai
4  Karan   24   38000    Pune

In [6]:
df["AnnualSalary"] = df["Salary"] * 12
print(df)

    Name  Age  Salary    City  AnnualSalary
0   Amit   25   40000  Indore        480000
1  Rahul   32   65000  Mumbai        780000
2  Priya   28   55000   Delhi        660000
3   Neha   35   75000  Indore        900000
4  Karan   24   38000    Pune        456000

In [7]:
df["IsSenior"] = df["Age"] >= 30
print(df)

    Name  Age  Salary    City  AnnualSalary  IsSenior
0   Amit   25   40000  Indore        480000     False
1  Rahul   32   65000  Mumbai        780000      True
2  Priya   28   55000   Delhi        660000     False
3   Neha   35   75000  Indore        900000      True
4  Karan   24   38000    Pune        456000     False