In [21]:
import pandas as pd
data = {
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Ankit"],
    "Age": [25, 30, 28, 35,27],
    "Salary": [40000, 60000, 55000, 75000,45000],
    "City": ["Indore", "Mumbai", "Delhi", "Indore","Kota"]
}

df = pd.DataFrame(data)


print(df.head)

<bound method NDFrame.head of     Name  Age  Salary    City
0   Amit   25   40000  Indore
1  Rahul   30   60000  Mumbai
2  Priya   28   55000   Delhi
3   Neha   35   75000  Indore
4  Ankit   27   45000    Kota>

In [10]:
df.describe()

             Age       Salary
count   4.000000      4.00000
mean   29.500000  57500.00000
std     4.203173  14433.75673
min    25.000000  40000.00000
25%    27.250000  51250.00000
50%    29.000000  57500.00000
75%    31.250000  63750.00000
max    35.000000  75000.00000

In [11]:
df["Name"]

0     Amit
1    Rahul
2    Priya
3     Neha
Name: Name, dtype: str

In [19]:
df.loc[0:2,["Name", "Salary"]]

    Name  Salary
0   Amit   40000
1  Rahul   60000
2  Priya   55000

In [22]:
df.shape

(5, 4)

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Amit", "Rahul", "Priya", "Neha", "Karan", "Rahul"],
    "Age": [25, 32, 28, 35, np.nan, 32],
    "Department": ["QA", "Dev", "QA", "Dev", "QA", "Dev"],
    "Salary": [40000, 65000, 55000, 75000, np.nan, 65000],
    "City": ["Indore", "Mumbai", "Delhi", "Indore", "Pune", "Mumbai"]
})

In [3]:
m = np.isnan(df["Age"]).sum()
print(m)
m = np.isnan(df["Salary"]).sum()
print(m)

1
1

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].median())
print(df)

    Name   Age Department   Salary    City
0   Amit  25.0         QA  40000.0  Indore
1  Rahul  32.0        Dev  65000.0  Mumbai
2  Priya  28.0         QA  55000.0   Delhi
3   Neha  35.0        Dev  75000.0  Indore
4  Karan  30.4         QA      NaN    Pune
5  Rahul  32.0        Dev  65000.0  Mumbai

In [7]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)

    Name   Age Department   Salary    City
0   Amit  25.0         QA  40000.0  Indore
1  Rahul  32.0        Dev  65000.0  Mumbai
2  Priya  28.0         QA  55000.0   Delhi
3   Neha  35.0        Dev  75000.0  Indore
4  Karan  30.4         QA  60000.0    Pune
5  Rahul  32.0        Dev  65000.0  Mumbai

In [14]:
filter = df[(df["Age"]>=30) & (df["Salary"]>60000)]
print(filter["Name"])

1    Rahul
3     Neha
5    Rahul
Name: Name, dtype: str

In [20]:
df.sort_values("Salary", ascending=False)

    Name   Age Department   Salary    City
3   Neha  35.0        Dev  75000.0  Indore
1  Rahul  32.0        Dev  65000.0  Mumbai
5  Rahul  32.0        Dev  65000.0  Mumbai
4  Karan  30.4         QA  60000.0    Pune
2  Priya  28.0         QA  55000.0   Delhi
0   Amit  25.0         QA  40000.0  Indore

In [21]:
df["AnnualSalary"] = df["Salary"]*12

print(df)

    Name   Age Department   Salary    City  AnnualSalary
0   Amit  25.0         QA  40000.0  Indore      480000.0
1  Rahul  32.0        Dev  65000.0  Mumbai      780000.0
2  Priya  28.0         QA  55000.0   Delhi      660000.0
3   Neha  35.0        Dev  75000.0  Indore      900000.0
4  Karan  30.4         QA  60000.0    Pune      720000.0
5  Rahul  32.0        Dev  65000.0  Mumbai      780000.0

In [27]:
r=df.groupby("Department")["Salary"].mean()
print(r.idxmax())

Dev

In [29]:
res = df.groupby("Department").agg(Min_sal=("Salary","min"), Max_sal = ("Salary", "max"), Avg_sal=("Salary", "mean"), Num_emp=("Name", "count"))

print(res)

            Min_sal  Max_sal       Avg_sal  Num_emp
Department
Dev         65000.0  75000.0  68333.333333        3
QA          40000.0  60000.0  51666.666667        3

In [31]:
df["AgeGroup"] = df["Age"].apply(lambda x: "Senior" if x>=30 else "Junior")
print(df)

    Name   Age Department   Salary    City  AnnualSalary AgeGroup
0   Amit  25.0         QA  40000.0  Indore      480000.0   Junior
1  Rahul  32.0        Dev  65000.0  Mumbai      780000.0   Senior
2  Priya  28.0         QA  55000.0   Delhi      660000.0   Junior
3   Neha  35.0        Dev  75000.0  Indore      900000.0   Senior
4  Karan  30.4         QA  60000.0    Pune      720000.0   Senior
5  Rahul  32.0        Dev  65000.0  Mumbai      780000.0   Senior

In [32]:
bonus = pd.DataFrame({
    "Name": ["Amit", "Rahul", "Priya", "Neha"],
    "Bonus": [5000, 8000, 6000, 10000]
})

In [33]:
avg_bonus = bonus["Bonus"].mean()
print(avg_bonus)

7250.0